"""CRUD for the ``link_suggestions`` table (LKPR-99).

Stores candidate link pairs generated by the sweep engine. All suggestions
use canonical pair ordering — min(id1, id2) as source, max(id1, id2) as
target — enforced by the store layer.
"""

from __future__ import annotations

import sqlite3
import uuid
from datetime import UTC, datetime, timedelta

from lorekeeper.models import LinkSuggestion
from lorekeeper.services.database import Database


def _now() -> str:
    return datetime.now(UTC).isoformat()


class LinkSuggestionStore:
    """CRUD for the ``link_suggestions`` table."""

    def __init__(self, db: Database) -> None:
        self._db = db
        self._conn = db.conn

    # ── Pair ordering ───────────────────────────────────────────────────────

    @staticmethod
    def _canonical(a: str, b: str) -> tuple[str, str]:
        return (a, b) if a < b else (b, a)

    # ── CRUD ────────────────────────────────────────────────────────────────

    def insert_suggestion(
        self,
        source_memory_id: str,
        target_memory_id: str,
        source_title: str,
        target_title: str,
        weighted_score: float,
        cosine_score: float = 0.0,
        bm25_score: float = 0.0,
        entity_score: float = 0.0,
        temporal_score: float = 0.0,
        suggested_type: str | None = None,
        confidence: str = "standard",
        status: str = "pending",
        id: str | None = None,
    ) -> LinkSuggestion:
        src, tgt = self._canonical(source_memory_id, target_memory_id)
        now = _now()
        s = LinkSuggestion(
            id=id or str(uuid.uuid4()),
            source_memory_id=src,
            target_memory_id=tgt,
            source_title=source_title,
            target_title=target_title,
            weighted_score=weighted_score,
            cosine_score=cosine_score,
            bm25_score=bm25_score,
            entity_score=entity_score,
            temporal_score=temporal_score,
            suggested_type=suggested_type,
            confidence=confidence,
            status=status,
            created_at=now,
            updated_at=now,
        )
        self._conn.execute(
            """INSERT INTO link_suggestions
               (id, source_memory_id, target_memory_id, source_title, target_title,
                weighted_score, cosine_score, bm25_score, entity_score, temporal_score,
                suggested_type, confidence, status, created_at, updated_at)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
            (s.id, s.source_memory_id, s.target_memory_id,
             s.source_title, s.target_title,
             s.weighted_score, s.cosine_score, s.bm25_score,
             s.entity_score, s.temporal_score,
             s.suggested_type, s.confidence, s.status,
             s.created_at, s.updated_at),
        )
        return s

    def upsert_suggestion(
        self,
        source_memory_id: str,
        target_memory_id: str,
        source_title: str,
        target_title: str,
        weighted_score: float,
        cosine_score: float = 0.0,
        bm25_score: float = 0.0,
        entity_score: float = 0.0,
        temporal_score: float = 0.0,
        suggested_type: str | None = None,
        confidence: str = "standard",
        status: str = "pending",
        id: str | None = None,
    ) -> LinkSuggestion:
        src, tgt = self._canonical(source_memory_id, target_memory_id)
        now = _now()
        s = LinkSuggestion(
            id=id or str(uuid.uuid4()),
            source_memory_id=src,
            target_memory_id=tgt,
            source_title=source_title,
            target_title=target_title,
            weighted_score=weighted_score,
            cosine_score=cosine_score,
            bm25_score=bm25_score,
            entity_score=entity_score,
            temporal_score=temporal_score,
            suggested_type=suggested_type,
            confidence=confidence,
            status=status,
            created_at=now,
            updated_at=now,
        )
        self._conn.execute(
            """INSERT OR REPLACE INTO link_suggestions
               (id, source_memory_id, target_memory_id, source_title, target_title,
                weighted_score, cosine_score, bm25_score, entity_score, temporal_score,
                suggested_type, confidence, status, created_at, updated_at)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)""",
            (s.id, s.source_memory_id, s.target_memory_id,
             s.source_title, s.target_title,
             s.weighted_score, s.cosine_score, s.bm25_score,
             s.entity_score, s.temporal_score,
             s.suggested_type, s.confidence, s.status,
             s.created_at, s.updated_at),
        )
        return s

    def get_suggestion(self, suggestion_id: str) -> LinkSuggestion | None:
        row = self._conn.execute(
            "SELECT * FROM link_suggestions WHERE id = ?", (suggestion_id,)
        ).fetchone()
        return _row_to_suggestion(row) if row else None

    def get_suggestions_for_memory(
        self, memory_id: str, status: str | None = None
    ) -> list[LinkSuggestion]:
        if status:
            rows = self._conn.execute(
                "SELECT * FROM link_suggestions "
                "WHERE (source_memory_id = ? OR target_memory_id = ?) AND status = ?",
                (memory_id, memory_id, status),
            ).fetchall()
        else:
            rows = self._conn.execute(
                "SELECT * FROM link_suggestions "
                "WHERE source_memory_id = ? OR target_memory_id = ?",
                (memory_id, memory_id),
            ).fetchall()
        return [_row_to_suggestion(r) for r in rows]

    def get_pending_suggestions(
        self, limit: int = 20, min_score: float = 0.0
    ) -> list[LinkSuggestion]:
        """Return pending suggestions ordered by weighted_score DESC.

        Args:
            limit: Maximum number of suggestions to return.
            min_score: Minimum weighted_score filter (inclusive).
        """
        rows = self._conn.execute(
            """SELECT * FROM link_suggestions
               WHERE status = 'pending' AND weighted_score >= ?
               ORDER BY weighted_score DESC
               LIMIT ?""",
            (min_score, limit),
        ).fetchall()
        return [_row_to_suggestion(r) for r in rows]

    def count_pending_suggestions(self) -> int:
        """Total count of all pending suggestions (workload indicator)."""
        row = self._conn.execute(
            "SELECT COUNT(*) FROM link_suggestions WHERE status = 'pending'"
        ).fetchone()
        return row[0] if row else 0

    def update_suggestion_status(
        self, suggestion_id: str, status: str
    ) -> None:
        self._conn.execute(
            "UPDATE link_suggestions SET status = ?, updated_at = ? WHERE id = ?",
            (status, _now(), suggestion_id),
        )

    def delete_suggestion(self, suggestion_id: str) -> None:
        self._conn.execute(
            "DELETE FROM link_suggestions WHERE id = ?", (suggestion_id,)
        )

    def rejected_pairs(self) -> set[tuple[str, str]]:
        rows = self._conn.execute(
            "SELECT source_memory_id, target_memory_id FROM link_suggestions "
            "WHERE status = 'rejected'"
        ).fetchall()
        return {(r["source_memory_id"], r["target_memory_id"]) for r in rows}

    def prune_expired(self, ttl_days: int) -> int:
        cutoff = datetime.now(UTC) - timedelta(days=ttl_days)
        cursor = self._conn.execute(
            "DELETE FROM link_suggestions WHERE updated_at < ?",
            (cutoff.isoformat(),),
        )
        return cursor.rowcount


def _row_to_suggestion(row: sqlite3.Row) -> LinkSuggestion:
    return LinkSuggestion(
        id=row["id"],
        source_memory_id=row["source_memory_id"],
        target_memory_id=row["target_memory_id"],
        source_title=row["source_title"],
        target_title=row["target_title"],
        weighted_score=row["weighted_score"],
        cosine_score=row["cosine_score"],
        bm25_score=row["bm25_score"],
        entity_score=row["entity_score"],
        temporal_score=row["temporal_score"],
        suggested_type=row["suggested_type"],
        confidence=row["confidence"],
        status=row["status"],
        created_at=row["created_at"],
        updated_at=row["updated_at"],
    )
